### PR TITLE
[BUGFIX] Handle adding namespaces to ignored namespaces

### PR DESCRIPTION
**Pull request by NamelessCoder**
Corrects the following two misbehaviors:

1. A second call to add a namespace with a `null` value causes an error; expected: silently keep ignoring namespace.
2. A second call to add a namespace that was previously ignored causes an error; expected: converts ignored namespace to active.

Fixes: #282

### CODE REVIEW

**Comment by opi99** [comment]
Patch fixes the issue from #282

**Comment by tiger-tw** [comment]
This fix is not included in 8.7.6. When will it be published in an offical release?
Many thanks for working on this!

**Comment by NamelessCoder** [comment]
This is really more of a question for the framework using Fluid as a composer dependency. The fix *is* published in an official release as far as Fluid itself is concerned.

Generally speaking: use `composer update typo3fluid/fluid` to update the Fluid dependency or set the minimum required Fluid version to `^2.4` if your project requires it.

**Comment by tiger-tw** [comment]
Ah ok, sorry for misunderstanding. 
I was thinking that Typo3 itself would be automatically updated. Thanks for the hint

**Comment by opi99** [comment]
This issue should also go into a branch, so composer package information for TYPO3 v8 LTS can be updated.

**Comment by NamelessCoder** [comment]
Guys, please don't put TYPO3 CMS questions and requests here. Try to keep this to the Fluid library alone. As stated above, this patch *is already released in tagged version 2.4.0 of Fluid* so it is up to third party frameworks whether they want to bump this dependency or just let users do `composer update typo3fluid/fluid`.

**Pull request merged**
