### PR TITLE
[DOC] Align with new TYPO3 documentation standards

### PR DESCRIPTION
**Pull request by alexander-nitsche**
Hi @lolli42,

this PR is a suggestion to align your package documentation with the recently introduced TYPO3 documentation standards [1][2].

I mainly added the basic file structure in Documentation/, transformed all Markdown into reST, added badges in README and additional sources (repository and docs.typo3.org) in composer.json.

Greetings, Alex

[1] https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/FileStructure.html
[2] https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/UserRoundTrip.html

Relates: https://github.com/TYPO3-Documentation/T3DocTeam/issues/182

### CODE REVIEW

**Review by mbrodala — APPROVED** [review]

**Comment by alexander-nitsche** [comment]
What is missing:
- Registering this documentation for rendering and publishing at docs.typo3.org with the [webhook](https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingDocForExtension/Webhook.html#github).
- Replacing links to outdated Markdown pages (docs/) with up-to-date reST pages (Documentation/), see
  ```
  t3docs-tools (main)$ ./bash/get-repos.sh all all
  t3docs-tools (main)$ ./bash/exec-repos.sh "grep -rnI 'github.com/TYPO3/Fluid/blob' --exclude-dir='.git' --exclude-dir='Documentation-GENERATED-temp' ." all

  ------------------------------------------------------------------------
  github.com/typo3-documentation/TYPO3CMS-Book-ExtbaseFluid/10.4: 1 result(s)
  ------------------------------------------------------------------------
  ./Documentation/8-Fluid/8-developing-a-custom-viewhelper.rst:14:https://github.com/TYPO3/Fluid/blob/master/doc/FLUID_CREATING_VIEWHELPERS.md.
  ------------------------------------------------------------------------
  github.com/typo3-documentation/TYPO3CMS-Book-ExtbaseFluid/11.5: 1 result(s)
  ------------------------------------------------------------------------
  ./Documentation/8-Fluid/8-developing-a-custom-viewhelper.rst:17:https://github.com/TYPO3/Fluid/blob/master/doc/FLUID_CREATING_VIEWHELPERS.md.
  ------------------------------------------------------------------------
  github.com/typo3-documentation/TYPO3CMS-Book-ExtbaseFluid/8.7: 1 result(s)
  ------------------------------------------------------------------------
  ./Documentation/8-Fluid/8-developing-a-custom-viewhelper.rst:14:https://github.com/TYPO3/Fluid/blob/master/doc/FLUID_CREATING_VIEWHELPERS.md.
  ------------------------------------------------------------------------
  github.com/typo3-documentation/TYPO3CMS-Book-ExtbaseFluid/9.5: 1 result(s)
  ------------------------------------------------------------------------
  ./Documentation/8-Fluid/8-developing-a-custom-viewhelper.rst:14:https://github.com/TYPO3/Fluid/blob/master/doc/FLUID_CREATING_VIEWHELPERS.md.
  ------------------------------------------------------------------------
  github.com/typo3-documentation/TYPO3CMS-Book-ExtbaseFluid/main: 1 result(s)
  ------------------------------------------------------------------------
  ./Documentation/8-Fluid/8-developing-a-custom-viewhelper.rst:17:https://github.com/TYPO3/Fluid/blob/master/doc/FLUID_CREATING_VIEWHELPERS.md.
  ------------------------------------------------------------------------
  github.com/typo3-documentation/TYPO3CMS-Reference-CoreApi/10.4: 2 result(s)
  ------------------------------------------------------------------------
  ./Documentation/ApiOverview/Fluid/Introduction.rst:271:* `The Fluid Syntax <https://github.com/TYPO3/Fluid/blob/master/doc/FLUID_SYNTAX.md>`__
  ./Documentation/ApiOverview/Fluid/Introduction.rst:272:* `ViewHelpers - what these classes do in the Fluid language <https://github.com/TYPO3/Fluid/blob/master/doc/FLUID_VIEWHELPERS.md>`__
  ------------------------------------------------------------------------
  github.com/typo3-documentation/TYPO3CMS-Reference-CoreApi/11.5: 2 result(s)
  ------------------------------------------------------------------------
  ./Documentation/ApiOverview/Fluid/Introduction.rst:290:* `The Fluid Syntax <https://github.com/TYPO3/Fluid/blob/master/doc/FLUID_SYNTAX.md>`__
  ./Documentation/ApiOverview/Fluid/Introduction.rst:291:* `ViewHelpers - what these classes do in the Fluid language <https://github.com/TYPO3/Fluid/blob/master/doc/FLUID_VIEWHELPERS.md>`__
  ------------------------------------------------------------------------
  github.com/typo3-documentation/TYPO3CMS-Reference-CoreApi/main: 2 result(s)
  ------------------------------------------------------------------------
  ./Documentation/ApiOverview/Fluid/Introduction.rst:290:* `The Fluid Syntax <https://github.com/TYPO3/Fluid/blob/main/doc/FLUID_SYNTAX.md>`__
  ./Documentation/ApiOverview/Fluid/Introduction.rst:291:* `ViewHelpers - what these classes do in the Fluid language <https://github.com/TYPO3/Fluid/blob/main/doc/FLUID_VIEWHELPERS.md>`__
  ------------------------------------------------------------------------
  Total: 11 result(s)
  ------------------------------------------------------------------------
  ```

**Comment by NamelessCoder** [comment]
I guess I'm out of the decision-making loop since I'm no longer Fluid maintainer, but my two cents are that I'm not a fan of this change, because:

* It makes the docs appear more "TYPO3 CMS only" - the doc'ing standards are taken from TYPO3 CMS, there are links to TYPO3 CMS specific implementation info (Settings.cfg being the biggest culprit). The original intention was opposite - to make it very clear that Fluid isn't "TYPO3 CMS only", it's just used by TYPO3 CMS.
* It adds dependency on Sphinx to render docs and when viewed on GitHub there are now meaningless files like "sitemap.rst" and "genindex.rst".
* The official doc URLs are now moved to the same place that exclusively renders TYPO3 CMS documentation, making the "Fluid is standalone" aspect even less apparent.
* RST doesn't render the single-backtick enclosed code pieces correctly (fixable by double-backtick'ing).
* There is now unused boilerplate stuff that communicates things like `tsconfig` and `typoscript` source highlighting, none of which should ever make it's way into Fluid docs (the engine repo should never document how to use itself with TYPO3 CMS, the opposite should always be the case). Somewhat fixable by removing these boilerplates.
* The correct commit prefix is `[DOC]` (fixable "in post" by making sure to change the squashed commit title).

The last three items are of course easily fixable. My main objection lies in the first three items. In short, I would prefer *less* coupling to TYPO3 CMS and I oppose *more* coupling. My vote is therefore a "no" - but I no longer have the authority to make this decision.

**Comment by alexander-nitsche** [comment]
Hi Claus,

so, what you essentially miss is a unique branding of the Fluid documentation to underline its standalone character: An application, emerged from the TYPO3 community but not depending on the TYPO3 CMS. This feature is not supported yet by the current documentation process, but it should be supported in perspective. We should start a brain storming on it in a separate issue - other standalone applications like Surf would also benefit from it.

The current documentation process brings many benefits to the Fluid documentation, foremost 

- being browsable via the global search at docs.typo3.org
- being linkable via reST intersphinx from other manuals that validates the links on compilation
- having a rich set of reST content elements
- having a proper design (even if not yet underlining the standalone character)
- having a proper user's round trip, guiding him from code repository to docs to store (Packagist or TER)

but you would have to stick with a note in the description of the project, that it is a standalone package that does not depend on TYPO3 CMS - at the moment.

Greetings, Alex

**Comment by lolli42** [comment]
Hey.

My 2 cents on this.

First, it was me who asked Alexander for a transition of .md to .rst for the Fluid docs. Thanks Alexander for taking care of this!

My basic stance on this is quite straight: Markdown is fine for simple extensions that don't have much to say. I'm using that for instance for ext:styleguide and some others, it's sufficient and we don't need to bother with .rst details.
However, when docs become more complex and lengthy, markdown is really very limited. There are so many things like no proper linking, no basic markup like an info box, no table of content. These things really hurt when writing more than just a couple of sentences. There are ways to add all that with custom markdown extensions, but we have this in place for the entire ecosystem already with .rst already.

That's why I asked Alexander to provide an according patch.

I don't think the format of the documentation is the place to make clear this project is a library that can be used in non-typo3-cms as well. It does not harm to publish it on docs.typo3.org, which is our central documentation hub, the non-typo3-exclusive project surf publishes there as well. Giving surf and fluid a different look on docs.typo3.org is possible, but also not crucial, imho. I think it is enough if we make clear that Fluid can be used without typo3 as well in readme.md and the main .rst docs.

I get the point that the docs now include some 'typo3-docs-specific' rendering files, but I'm willing to accept this to still benefit from the main .rst advantages. We could streamline them, though, for instance I'd like to remove the commented includes things from Settings.cfg.

People not using the rendered version of the docs can still read the .rst files directly, similar to the .md files as before: github for instance tends to render them in a decent way, not perfect, but good enough to read them. The format isn't that much different to .md, too.

As such, I'll now give that PR a shot to see if the basic rendering is fine. If so, we'll go with a merge and see if the docs team can properly add it to docs.typo3.org. Fine tuning of the docs will then follow, I suppose.

**Review by lolli42 — APPROVED** [review]

**Pull request merged**
