### PR TITLE
[BUGFIX] Respect $ignoreUnknown when rendering section/partial

### PR DESCRIPTION
**Pull request by NamelessCoder**
Somewhere, respect for $ignoreUnknown was lost. This patch
adds a check and only throws the exception if it is false.

### CODE REVIEW

**Comment by sascha-egerer** [comment]
Tests need to be adjusted, right?

**Comment by NamelessCoder** [comment]
Yes; there are a couple of tests to adjust before merging.

**Comment by NamelessCoder** [comment]
Patch is now ready to be considered. Had to specifically catch both template file and section missing exceptions and check $ignoreUnknown to prevent falling through to catching of generic View exceptions.

**Comment by opi99** [comment]
Code looks good for me ... where can I find the changes in the tests?

**Comment by NamelessCoder** [comment]
FYI: there are no changes in the tests as these specific cases are unfortunately not covered (the unit tests that do test for optional, don't test the ViewHelper). The code does get executed and is confirmed in production - but there are no assertions on that behavior to try/catch in the VH itself.

**Pull request merged**
