### PR TITLE
[BUGFIX] Prevent binary characters in compiled templates

### PR DESCRIPTION
**Pull request by mbrodala**
When compiled templates are retrieved from the cache and contain binary characters, arbitrary behavior may occur, usually a huge pile of Chinese-like characters is outputted and the template class cannot be loaded. Avoid this by delegating the generation of the compiled node state to the node converter.

### CODE REVIEW

**Comment by mbrodala** [comment]
I'll fix the failing tests later.

**Comment by mbrodala** [comment]
A bit more background: the binary characters come from the serialization of objects with protected or private properties since PHP mangles their names using 0 (null) bytes.

**Comment by NamelessCoder** [comment]
Please use `PHP_EOL` instead of `chr(10)`. You could also easily sell this one as a TASK to clean up the conversion of VH argument nodes / removing duplicated conversion.

**Comment by mbrodala** [comment]
I tried to stick to the line endings used in the `TemplateCompiler`. Personally I'd prefer `"\n"` or even heredoc where possible.

**Comment by NamelessCoder** [comment]
I'd welcome a PR that string-replaces `chr(10)` with `PHP_EOL` - some of these are nearly a decade old by now ;)

**Comment by mbrodala** [comment]
Sure thing, but first I'd like to see this one fixed. ;-)

**Pull request merged**
