### PR TITLE
[BUGFIX] Change order of checking matches to prevent mistakenly parse arrays as identifier

### PR DESCRIPTION
**Pull request by dlubitz**
To solve #449, we can change the order of result handling. Tests were added, which test for the existing behavior.

### CODE REVIEW

**Comment by NamelessCoder** [comment]
See history of discussion on https://github.com/TYPO3/Fluid/pull/493

**Comment by NamelessCoder** [comment]
I would love to separate the tests to a dedicated pull request, which would confirm the existing behavior without the change to processing order.

**Comment by dlubitz** [comment]
Sure, can do this. Will create another PR.

**Comment by radmiraal** [comment]
I just applied those changes on a Neos installation where all backend module broke (core + custom), and I can confirm that the errors have gone away and everything still seems to work fine :) Nice!

**Comment by dlubitz** [comment]
See https://github.com/TYPO3/Fluid/pull/507

**Comment by NamelessCoder** [comment]
Tests PR merged - I'm very eager to have someone (@radmiraal?) do a test on an affected system to confirm that these new tests will fail.

**Comment by radmiraal** [comment]
And there I found installing myself downloading composer on a non-dev system for the first time in years... :)

I ran the tests, unfortunately there are failures :(

https://gist.github.com/radmiraal/3451988b880292deb9e98d89277749c9

**Comment by dlubitz** [comment]
>I ran the tests, unfortunately there are failures :(

Actually, this is great 🎉! As the tests are running currently without the fix.

**Comment by radmiraal** [comment]
aah, I thought it also had the fix applied ;) Are those all the expected failures?

**Comment by dlubitz** [comment]
1-6 yes. And 7+8 I guess are more related to some misconfigration of the tests. But @NamelessCoder should know better.

**Comment by NamelessCoder** [comment]
Great, thanks @radmiraal - the first failures were very much expected on affected systems. But 7 and 8 are *not* expected and is an indication that the fix would break existing behaviors on those systems that are affected by the PCRE issue (. This has to go back to the drawing board, unfortunately.

@dlubitz If there is a solution to this then I expect it has to be by adapting the regular expressions, like you touched on in the first iteration of your patch.

**Comment by dlubitz** [comment]
> @dlubitz If there is a solution to this then I expect it has to be by adapting the regular expressions, like you touched on in the first iteration of your patch.

As we discussed in Neos Community, we (@albe ) expect an error in the recursion of the regex, which sounds very likely.

> I think the actual issue is in the recursive match in Subarray - the following will match a ValueIdentifier but that is then written into the first level matches

**Comment by dlubitz** [comment]
@NamelessCoder Actually the fix also fixes the broken tests 7+8. They are broken atm in this specific environment anyways. With the fix they are also fixed.

Maybe @radmiraal can checkout my branch (test incl. fix) and run it again. Should be green than (except of error 1 - because it operates directly on the regex)

**Comment by dlubitz** [comment]
I emulated the behavior with following code:
```
protected function recursiveArrayHandler($arrayText)
    {
        $matches = [];
        $arrayToBuild = [];
        if (preg_match_all(Patterns::$SPLIT_PATTERN_SHORTHANDSYNTAX_ARRAY_PARTS, $arrayText, $matches, PREG_SET_ORDER)) {
            foreach ($matches as $singleMatch) {
                $arrayKey = $this->unquoteString($singleMatch['Key']);

                /* Emulate regex parse error */
                if (array_key_exists('Subarray', $singleMatch) && !empty($singleMatch['Subarray'])) {
                    $singleMatch['Subarray'];
                    $false = substr($singleMatch['Subarray'], strpos($singleMatch['Subarray'], ': ')+2);
                    $false = substr($false, 0, strpos($false, ',') === false ? strlen($false): strpos($false, ','));
                    if (preg_match('#(?:(?=[^,{}\.]*[a-zA-Z])[a-zA-Z0-9_-]*)(?:\\.[a-zA-Z0-9_-]+)*#x', $false)) {
                        $singleMatch['VariableIdentifier'] = $false;
                    }
                }
                /* END - Emulate regex parse error */


                if (!empty($singleMatch['VariableIdentifier'])) {
                    $arrayToBuild[$arrayKey] = new ObjectAccessorNode($singleMatch['VariableIdentifier']);
                } elseif (array_key_exists('Number', $singleMatch) && (!empty($singleMatch['Number']) || $singleMatch['Number'] === '0')) {
                    // Note: this method of casting picks "int" when value is a natural number and "float" if any decimals are found. See also NumericNode.
                    $arrayToBuild[$arrayKey] = $singleMatch['Number'] + 0;
                } elseif ((array_key_exists('QuotedString', $singleMatch) && !empty($singleMatch['QuotedString']))) {
                    $argumentString = $this->unquoteString($singleMatch['QuotedString']);
                    $arrayToBuild[$arrayKey] = $this->buildArgumentObjectTree($argumentString);
                } elseif (array_key_exists('Subarray', $singleMatch) && !empty($singleMatch['Subarray'])) {
                    $arrayToBuild[$arrayKey] = new ArrayNode($this->recursiveArrayHandler($singleMatch['Subarray']));
                } 
            }
        }
        return $arrayToBuild;
    }
```

**Comment by albe** [comment]
> Must not be merged, as this would simply move the problem and/or hide it - not solve it. See test failures on https://gist.github.com/radmiraal/3451988b880292deb9e98d89277749c9. The first set of failures are expected on affected systems but the last half indicate that moving this match merely makes other variable matching behave unexpectedly.

@NamelessCoder since @radmiraal ran just the additional tests without the fix, the additional failures only hint at other things that are inherently wrong on the affected systems. So another run with both tests+fix as @dlubitz suggested should show this change is safe to add (given all tests also still pass on "normal" systems )

**Comment by radmiraal** [comment]
if anyone is interested in an affected system... let me know ;)

**Comment by dlubitz** [comment]
@radmiraal run the tests of this PR with expected result:

```
 PHPUnit 8.5.2 by Sebastian Bergmann and contributors.
 
 .............................................................   61 / 1179 (  5%)
 .............................................................  122 / 1179 ( 10%)
 .............................................................  183 / 1179 ( 15%)
 .............................................................  244 / 1179 ( 20%)
 .............................................................  305 / 1179 ( 25%)
 ...................................F.........................  366 / 1179 ( 31%)
 .............................................................  427 / 1179 ( 36%)
 .............................................................  488 / 1179 ( 41%)
 .............................................................  549 / 1179 ( 46%)
 .............................................................  610 / 1179 ( 51%)
 .............................................................  671 / 1179 ( 56%)
 .............................................................  732 / 1179 ( 62%)
 .............................................................  793 / 1179 ( 67%)
 .............................................................  854 / 1179 ( 72%)
 .............................................................  915 / 1179 ( 77%)
 ........SSSSSSSSSSSSSSSSSSSS..................SSSSSSSSSSSSSSS  976 / 1179 ( 82%)
 SSS......................................SSSSSSSSSSSSSSSSSSSS 1037 / 1179 ( 87%)
 SSSSSSSSSSSSSSSSSS.S...SSS...................SSSSSSSSSSSSSSSS 1098 / 1179 ( 93%)
 SSS..SS.........SSSSSSSSS..........S......................... 1159 / 1179 ( 98%)
 ....................                                          1179 / 1179 (100%)
 
 Time: 589 ms, Memory: 36.00 MB
 
 There was 1 failure:
 
 1) TYPO3Fluid\Fluid\Tests\Unit\Core\Parser\PatternsTest::testSPLIT_PATTERN_SHORTHANDSYNTAX_ARRAY_PARTS
 The regular expression splitting the array apart does not work!
 Failed asserting that two arrays are equal.
 --- Expected
 +++ Actual
 @@ @@
          1 => 'e: {c:d, "e#":f, 'g': "h"}'
          'Key' => 'e'
          2 => 'e'
 -        'QuotedString' => ''
 -        3 => ''
 -        'VariableIdentifier' => ''
 -        4 => ''
 +        'QuotedString' => '"h"'
 +        3 => '"h"'
 +        'VariableIdentifier' => 'f'
 +        4 => 'f'
          'Number' => ''
          5 => ''
          'Subarray' => 'c:d, "e#":f, 'g': "h"'
 
 /home/schouwen-duiveland/fluid-bug/Fluid/tests/Unit/Core/Parser/TemplateParserPatternTest.php:420
 
 FAILURES!
 Tests: 1179, Assertions: 1770, Failures: 1, Skipped: 111.

```
So I would assume this as a solid fix. WDYT @NamelessCoder ?

**Comment by LarsNieuwenhuizen** [comment]
Using this branch resolves our issues with arrays being parsed as strings on php7.3.12 - nginx with php-fpm on CentOS7.

**Comment by dlubitz** [comment]
@NamelessCoder Still objections? Anything I can provide to get this done?

**Comment by NamelessCoder** [comment]
Currently busy with other projects but will get back to this asap. If this ends up being the solution I will instead merge https://github.com/TYPO3/Fluid/pull/493 since it's identical and Sebastian was first and hasn't yet had any patches merged.

**Comment by NamelessCoder** [comment]
Replaced by https://github.com/TYPO3/Fluid/pull/493 which is functionally identical.

**Pull request closed without merging**
