### PR TITLE
[BUGFIX] Allow variables in Snakecase in expressions and ternaries

### PR DESCRIPTION
**Pull request by Atsyn**
Resolves: #420

### CODE REVIEW

**Comment by liayn** [comment]
I guess we need the same for boolean expressions and ternaries

**Comment by Atsyn** [comment]
Updated for all expressions and ternaries.

**Comment by mbrodala** [comment]
@NamelessCoder I've always seen the same tests failing locally that now fail on Travis. Any idea what's going on here?

**Comment by sascha-egerer** [comment]
> @mbrodala Stack trace is strange.
> Error not related with Fluid. =(

I think @mbrodala means the failing tests and not the deprecation warnings. So there is no stacktrace for the tests. There are just 2 items in the wrong order.

**Comment by NamelessCoder** [comment]
@mbrodala We switched from `glob()` to recursive DirectoryIterator:

https://github.com/TYPO3/Fluid/commit/6beef025fe3c1071c5994a7700f8efe3469dcdce#diff-7892b10d8d052eaed47516c29d922827

It's possible something changed in how DirectoryIterator sorts files, or how PHPUnit determines equalness when calling `assertEquals` with two arrays as input (when before it didn't care about order, now it does). It would be nice to prepare another PR that changes these two tests to check if all expected items are contained without caring about the order.

**Comment by NamelessCoder** [comment]
Passing `true` as 4th parameter for `assertEquals` causes arrays to be sorted before comparison:

https://github.com/sebastianbergmann/comparator/blob/master/src/ArrayComparator.php#L46

**Comment by NamelessCoder** [comment]
Seems like our PHPUnit version is also terribly outdated and lacks this parameter - and it's going to take quite some work to get it updated...

**Comment by Atsyn** [comment]
@mbrodala do you mean my changes with variables?

**Comment by mbrodala** [comment]
Yeah, basically just add a `snail_cased` variable to the existing tests of all classes that where changed.

**Comment by mbrodala** [comment]
I'd still love to have a test for this ...

**Comment by NamelessCoder** [comment]
@mbrodala I would merge this w/o requiring unit tests to cover it. This is actually a case of the TemplateParser Patterns not being reproduced correctly in the expression node types. The longer-perspective solution would be to somehow refactor, making the variable detection parts central in TemplateParser and then providing thorough tests (that also behave as declarative "which variable names do we actually support?" type info). 

Finally this then logically leads to somehow refactoring TemplateParser's many different usages of "a regexp to detect a variable reference". In my opinion, by loosening up the detection expressions entirely to allow anything, then using sub-detection to determine what type of node actually gets created (match variables with `.` and detect if garbage -> create TextNode instead of any Fluid-active type of node).

Assuming the switch to a lexer solution doesn't happen first...

**Comment by mbrodala** [comment]
Fine with me but it still feels unsafe to not have any code-written declaration that we support such variable names.

**Comment by NamelessCoder** [comment]
Amen to that. I'll take a look at this right away because those patterns are just... excessively hard to read.

**Pull request merged**
