### PR TITLE
[TASK] Migrate phpdoc VH markup to common syntax

### PR DESCRIPTION
**Pull request by sypets**
This is based on the PR #436 by @DanielSiepmann and the suggestions in issue #512. 

A summary of the used markup is in my gist: https://gist.github.com/sypets/360a62ce0685521049a65be366edbbef

Following changes were performed:

- removed admonitions (note, caution)
- removed textroles, e.g. :xml:. Use just double-backticks for inline code.
- removed :ref:
- If the text was in a note, I moved it to the top (if it is important enough to warrant a note, I think it should exist before the examples)

### CODE REVIEW

**Comment by DanielSiepmann** [comment]
I've rendered the change of @sypets. You can find the result here: https://tmp.daniel-siepmann.de/projects/typo3/typo3fluid-fluid-rendered-reference/Index.html

**Comment by sypets** [comment]
Relevant for this change are only typo3fluid/fluid: https://tmp.daniel-siepmann.de/projects/typo3/typo3fluid-fluid-rendered-reference/typo3fluid/fluid/latest/Index.html

The output looks good. :smile: I could see no obvious errors or problems.

**Comment by sypets** [comment]
Ping.

How can we proceed here?

**Review by mbrodala — APPROVED** [review]

**Comment by mbrodala** [comment]
Will continue in #527

**Pull request closed without merging**
