### PR TITLE
Escape single quotes in cache static viewhelper

### PR DESCRIPTION
**Pull request by tmotyl**
fixes: https://github.com/TYPO3/Fluid/issues/517

### CODE REVIEW

**Comment by NamelessCoder** [comment]
Tested, confirmed, merged.

**Comment by tmotyl** [comment]
Thank you!

**Comment by tmotyl** [comment]
Should it be backported to some branches?

**Comment by NamelessCoder** [comment]
> Should it be backported to some branches?

Yes, when releases are made next time this goes into all maintained 2.x branches by cherry pick.

**Pull request merged**
