### PR TITLE
[TASK] use (float) and (int)

### PR DESCRIPTION
**Pull request by DanielRuf**
See the performance difference at https://3v4l.org/eQaNr. Typecasting is generally faster than the functions.

### CODE REVIEW

**Comment by NamelessCoder** [comment]
Casting is preferred so if there are other occurrences it would be great to fix all of them in this patch.

**Comment by DanielRuf** [comment]
I did a full search for boolval, intval and floatval. I can check if there are more occurences, change them and push some more commits.

Will check this later today.

**Comment by NamelessCoder** [comment]
Thanks - and although I doubt there are any, don't forget to scan for `strval` vs. `(string)`.

**Comment by DanielRuf** [comment]
Right.

I might check some other things for future PR's, especially when it comes to unicode handling just to make sure that we are on the safe side and other "problematic" PHP functions and internals.

**Comment by DanielRuf** [comment]
> Thanks - and although I doubt there are any, don't forget to scan for strval vs. (string).

Found no occurence of `strval`.

**Comment by DanielRuf** [comment]
Should I also change the travis.yml config? 
> HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`.

**Comment by lolli42** [comment]
could you rebase the patch to current master? We just removed hhvm from .travis.yml.

**Comment by NamelessCoder** [comment]
Whomever merges this: don't forget to squash-and-merge and fix the commit casing; `[TASK] Use (float) and (int)` (uppercase "U")

**Comment by NamelessCoder** [comment]
FYI to all maintainers: I've enabled "Branch must be up to date" which means there's now an "Update branch" button - so we don't have to ask for rebases. Don't forget to always squash-and-merge after that so we avoid the merge commits ;)

**Comment by DanielRuf** [comment]
> FYI to all maintainers: I've enabled "Branch must be up to date" which means there's now an "Update branch" button - so we don't have to ask for rebases. Don't forget to always squash-and-merge after that so we avoid the merge commits ;)

Cool, thanks =)

**Pull request merged**
